export const NAV_MOVE_PAGE = 'NAV_MOVE_PAGE';

export const JOIN_ERROR = 'JOIN_ERROR';
export const JOIN_USER_PROPS_CHECK = 'JOIN_USER_PROPS_CHECK';

export const LOGIN_EMAIL_CHANGE = 'LOGIN_EMAIL_CHANGE';
export const LOGIN_PASSWORD_CHANGE = 'LOGIN_PASSWORD_CHANGE';
